export const SEARCH_TRUE = 'SEARCH_TRUE';
export const SEARCH_FALSE = 'SEARCH_FALSE';
export const SEARCH_ERROR = 'SEARCH_ERROR';
export const LOCATION_TRENDS = 'LOCATION_TRENDS';
export const TRENDING_TWEETS = 'TRENDING_TWEETS';
export const CACHE_GEO = 'CACHE_GEO';